version: "3.1"
services:
  springpsql:
    image: postgres
#    container_name: springpsql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=postgres
    volumes:
      - db:/var/lib/postgresql
    networks:
      - app-net
  userservices:
    image: anil76201/userimage
    ports:
      - 8082:8082
    depends_on:
      - springpsql
    networks:
      - app-net

  contactservices:
    image: anil76201/contactimage
    ports:
      - 8081:8081
    depends_on:
      - springpsql
    networks:
      - app-net

volumes:
  db:

networks:
  app-net:
